### ISSUE TITLE
Have another researcher review the wording on the report

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/interactive-templates#96]
To ensure the content within the Interactive report is technically accurate, we should have another researcher review the wording, as they will be able to compare it to what the code is doing.

**Comment by CLStables** [comment]
I'm not sure if this is relevant to this issue or a separate one, but things that I've noted down we should ask researchers to review are:

- That the options being chosen on the Analysis Request form match the study code
- That the descriptions of the results/methods in the report match the study code
- Is there anything else in the study code that is important for us to communicate to users?

**Comment by lucyb** [comment]
@LFISHER7 will ask Christine to do this.
Chris has produced a video of him reviewing the wording on the report, without looking at the code.

**Comment by HelenCEBM** [comment]
Hellloo - great to see how this has evolved! Some comments on the UTI report:

### 1. Title etc
What is this? 
![image](https://github.com/opensafely-core/interactive-templates/assets/24392156/da0550c4-a5f3-495c-90b7-7141d27387cc)

### 2. Measures:
  > The measure shows the number of people each month who had both a code from codelist 1 added to their health record and a code from codelist 2 added to their health record in the same month or up to 0 years before the start of that month. 
- The "0 years" might be confusing (I haven't looked at the request form yet but is there a months option rather than 0 years?)
- It doesn't describe that we're going to calculate a rate per 1000 so this might come as a surprise?
- I wonder if it might be a bit clearer if we show the measure in a box/table rather than describing in text, e.g.
    ![image](https://github.com/opensafely-core/interactive-templates/assets/24392156/2bab4676-2728-4a5c-ab6e-156a5c79160e)


### 3. Analysis limitations section 
  - this is quite a dense block of text that most people will probably skim over... can we make it easier to take in the key points e.g. for each point have a summary sentence followed by a bullet list?
  - The point after the "and/or" here doesn't seem to add much:
    > If the chosen codelists represent vaccinations, referrals, maternity records, or activities not directly occurring in primary care , note that some events may be recorded in way that are not fully captured by this analysis, and/or are subject to limited recording in primary care.

### 4. Practice-level variation
There appear to be 13 lines on this decile chart (?!) but no median
![image](https://github.com/opensafely-core/interactive-templates/assets/24392156/9235cfbd-c69c-4733-bccb-7b92ebadc0ea)
- Number of practices not shown: "The decile chart below is based on data from 0/2460 practices."
- Missing link: "You can read more about how we use deciles here."
- Maybe put the what-is-a-deciles chart in smaller font to make it look less busy?

**Comment by LFISHER7** [comment]
Thanks for all of the feedback @HelenCEBM. I've pulled all of the points out into individual issues. We haven't yet reviewed whether the generated report matches the study code. That's a bit more involved, so I've opened https://github.com/opensafely-core/interactive-templates/issues/178 to keep track of it. I'm closing this now that everything outstanding is tracked elsewhere
